title : Blog Rully
tagline: Walking Hand
author :
  name : Rully Agus
  email : blah@email.test
  github : rullyvm
  twitter : rullyvm
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
